server:
  port: 8082
spring:
  application:
    name: iiv
  datasource:
    url: jdbc:postgresql://172.16.16.29:5432/postgres?currentSchema=md
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true