server:
  port: 8081
spring:
  application:
    name: ssv
  datasource:
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=mh
    username: postgres
    password: 3431215
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
        time_zone: GMT+5
      jackson:
        time-zone: Asia/Tashkent
        deserialization:
          adjust-dates-to-context-time-zone: true