server:
  port: 8091
spring:
  application:
    name: dpm
  datasource:
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=dpm
    username: postgres
    password: 3431215
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
        time_zone: GMT+5
      jackson:
        time-zone: Asia/Tashkent
        deserialization:
          adjust-dates-to-context-time-zone: true
